---
galaxy_info:
  author: YAEGASHI Takeshi
  description: Contains blockinfile module
               to insert/update/remove a text block surrounded by marker lines
  license: GPLv3+
  min_ansible_version: 1.2
  categories:
  - system
dependencies: []
